version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo ============= Pre-Build =============
      - pwd
      - ls -al
      - aws s3 cp s3://teamcp2-secret-bucket/hibernate.properties src/main/resources/hibernate.properties
      - aws s3 cp s3://teamcp2-secret-bucket/application.properties src/main/resources/application.properties
      - ls -al
      - ls -al src/main/resources/
      - aws s3 rm --recursive s3://teamcp2-ui/*
  build:
    commands:
      - echo ============= Build =============
      - mvn package
      - cd angular
      - npm install
      - npm install -g @angular/cli
      - ng build
      - ls -al
  post_build:
    commands:
      - echo ============= Post-Build =============
      - cd dist/front
      - ls -al
      - aws s3 cp . s3://teamcp2-ui --recursive
      - cd ../../../
      - mv target/Team-C-P2-*.*.war ROOT.war
      - ls -al
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*